# Generated by Django 3.0.3 on 2020-05-07 08:22

import api.models
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('division', models.CharField(blank=True, choices=[('KCH', 'KUCHING'), ('SMH', 'KOTA SAMARAHAN'), ('SER', 'SERIAN'), ('SAM', 'SRI AMAN'), ('BTG', 'BETONG'), ('SKI', 'SARIKEI'), ('SBU', 'SIBU'), ('MKH', 'MUKAH'), ('BIN', 'BINTULU'), ('KPT', 'KAPIT'), ('MRI', 'MIRI'), ('LBG', 'LIMBANG')], max_length=3, null=True)),
                ('fullname', models.CharField(blank=True, max_length=50)),
                ('is_farmer', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='OfficeLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('div_office', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.OfficeLocation')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FarmerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True, max_length=20)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='farmer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_gps', models.CharField(blank=True, max_length=30, null=True)),
                ('farm_condition', models.CharField(blank=True, choices=[('B', 'BERBUKIT'), ('R', 'RATA'), ('L', 'LAIN-LAIN')], max_length=6, null=True)),
                ('farm_area', models.CharField(blank=True, choices=[('H1', 'Kurang daripada 1 hektar'), ('H2', '1–20 hektar'), ('H3', '21–40 hektar'), ('H4', '41–60 hektar'), ('H5', '61–80 hektar'), ('H6', '81–100 hektar'), ('H7', 'Lebih daripada 100 hektar')], max_length=2, null=True)),
                ('variety', models.CharField(blank=True, max_length=30, null=True)),
                ('vine_number', models.CharField(blank=True, choices=[('VN1', '100 atau kurang'), ('VN2', '101–300'), ('VN3', '301–500'), ('VN4', '501–700'), ('VN5', '701–900'), ('VN6', '901–1100'), ('VN7', '1101–1300'), ('VN8', '1301–1500'), ('VN9', '1501–1700'), ('VN10', '1701–1900'), ('VN11', '1901–2100'), ('VN12', '2101–2300'), ('VN13', '2301–2500'), ('VN14', '2501–2700'), ('VN15', '2701–2900'), ('VN16', '2901–3100'), ('VN17', '3101–3300'), ('VN18', '3301–3500'), ('VN19', '3501–3700'), ('VN20', '3701–3900'), ('VN21', '3901–4000'), ('VN22', 'Lebih daripada 4000')], max_length=5, null=True)),
                ('farm_age', models.CharField(blank=True, max_length=20)),
                ('slug', models.SlugField(blank=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='farmer_farm', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_gps', models.CharField(blank=True, max_length=30, null=True)),
                ('vine_no', models.CharField(blank=True, max_length=20)),
                ('vine_age', models.CharField(blank=True, max_length=20)),
                ('case_start_date', models.DateField()),
                ('case_subject', models.CharField(blank=True, max_length=200)),
                ('case_descriptions', models.CharField(blank=True, max_length=200)),
                ('vine_part', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to=api.models.upload_location)),
                ('case_reported_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('case_status', models.CharField(blank=True, choices=[('open', 'Buka'), ('processing', 'Sedang diproses'), ('closed', 'Tutup')], max_length=20)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
